### ISSUE TITLE
Not consistence parameter stoploss & pips name in getsizing function

### ISSUE THREAD

**Issue by santatic** [happydasch/btoandav20#64]
I have run `btoandav20` backtest and realtime testing.
On backtesting, I used class `OandaV20BacktestRiskPercentSizer` for sizing
And on realtime, I used class `OandaV20RiskPercentSizer` for sizing

Then I get a error when call function `getsizing` with parameter `pips` is not found in function `OandaV20RiskPercentSizer.getsizing`, because `OandaV20RiskPercentSizer.getsizing` called it is `stoploss`

Is it a in-consistence update, or we use it for any other intention?

**Comment by happydasch** [comment]
Hi, you are right. I did some changes lately to the backtest sizers and did not update the sizer var naming. will update the sizer to also use pips. Thanks for posting the issue.
