### ISSUE TITLE
Why no loop when call response =???

### ISSUE THREAD

**Issue by quantcn** [happydasch/btoandav20#70]
I am new to python. When I check btoandav10 shipped with backtrader, I see that in Class Streamer, we have:

def run(self, endpoint, params=None):
        # Override to better manage exceptions.
        # Kept as much as possible close to the original
        self.connected = True
       ...
        while self.connected:
            # Added exception control here
            try:
                response = self.client.get(url, **request_args)

Here we get response in a while loop.

While in btoandav20, in Class OandaV20Store, we have:
def _t_streaming_prices(self, dataname, q):
        '''Callback method for streaming prices'''
        try:
            response = self.oapi_stream.pricing.stream(
                self.p.account,
                instruments=dataname,
            )
There is no while loop. I wonder how this can get price data continuously. I think this "response =" will be executed only once.

I noticed '''Callback method for streaming prices''', could you point me out who will call back this method. I searched and only find that streaming_prices call this _t_streaming_prices method.

**Comment by happydasch** [comment]
the streaming is done in the feed:

https://github.com/happydasch/btoandav20/blob/57d466f98fbb41e5f8aa9024035c1b796695bdf1/btoandav20/feeds/oandav20feed.py#L398

**Comment by quantcn** [comment]
Sorry, I am still confused. in the oandav20feed, it uses self.qlive.get(timeout=self._qcheck))  to get bar data from qlive.
But what I am interested in is put bar data into qlive, not get. In the store20,  after response = self.oapi_stream.pricing.stream(
self.p.account, instruments=dataname), it will put bar data in response into qlive. I expect there should be a while loop to put data into the queue qlive, but there isn't, why?
