### ISSUE TITLE
401 (Unauthorized) on btoandav20 works ok on oandapyV20

### ISSUE THREAD

**Issue by faroutxxx** [happydasch/btoandav20#71]
Just all of a sudden stops working on long time running scripts. Multiple Oanda API demo accounts showing 401 (Unauthorized).
Created new account and generated new API same issue.
Same account/API key work via oandapyV20

**Comment by happydasch** [comment]
In most cases it is using the wrong token (live token for practice account or practice token for a live account) or a invalidated token. Please make sure, that you use the correct token. try to regenerate it and ensure you use the correct one. if that does not fix it, reopen this issue.
